var computers = {
  "classes of computers": {
    "cognitive computer": 0, 
    "computer": 10, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 1, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "cognitive computer": {
    "classes of computers": 0, 
    "computer": 3, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 9, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer": {
    "classes of computers": 3, 
    "cognitive computer": 0, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 5, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 1, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 1, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 24, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 3, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 8, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer addiction": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 107, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 101, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer architecture": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 102, 
    "computer addiction": 0, 
    "computer hardware": 2, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 5, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 11, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer hardware": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 1, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer hardware companies": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 80, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 3, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 10, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 8, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer insurance": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 18, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 1, 
    "computer hardware companies": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 1, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer maintenance": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 119, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 2, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 10, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer programming": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 53, 
    "computer addiction": 0, 
    "computer architecture": 1, 
    "computer hardware": 1, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 1, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 19, 
    "data centers": 1, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 1, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer rage": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 33, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 138, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer says no": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 12, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 29, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer systems": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 388, 
    "computer addiction": 0, 
    "computer architecture": 7, 
    "computer hardware": 6, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 1, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 33, 
    "data centers": 0, 
    "digital electronic computer": 2, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 8, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 6, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computer-related introductions by year": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 19, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 1, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computers and the environment": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 0, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "computing by computer model": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 14, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "data": 1, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "data": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 28, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 1, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "data centers": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 23, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 4, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 320, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 1, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "digital electronic computer": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 29, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 12, 
    "data centers": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 2, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "electronic media and sleep": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 0, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "endless computer": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 11, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 1, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "evaluation of computers": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 7, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "history of computing": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 250, 
    "computer addiction": 0, 
    "computer architecture": 2, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 1, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 1, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 33, 
    "data centers": 2, 
    "digital electronic computer": 1, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 6, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "information appliances": {
    "classes of computers": 1, 
    "cognitive computer": 0, 
    "computer": 21, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 2, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 1, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "laser 50": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 64, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 2, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "list of countries by computer exports": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 15, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 18, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "microcomputer": {
    "classes of computers": 3, 
    "cognitive computer": 0, 
    "computer": 98, 
    "computer addiction": 0, 
    "computer architecture": 1, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 1, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 17, 
    "data centers": 1, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 1, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "mixlink": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 7, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 3, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "motion history images": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 1, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "outline of computers": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "outline of computers": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 1, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "pcaas": 0, 
    "the eniac day": 0
  }, 
  "pcaas": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 0, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 0, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 0, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "the eniac day": 0
  }, 
  "the eniac day": {
    "classes of computers": 0, 
    "cognitive computer": 0, 
    "computer": 79, 
    "computer addiction": 0, 
    "computer architecture": 0, 
    "computer hardware": 0, 
    "computer hardware companies": 0, 
    "computer insurance": 0, 
    "computer maintenance": 0, 
    "computer programming": 0, 
    "computer rage": 0, 
    "computer says no": 0, 
    "computer systems": 0, 
    "computer-related introductions by year": 0, 
    "computers and the environment": 0, 
    "computing by computer model": 0, 
    "data": 9, 
    "data centers": 0, 
    "digital electronic computer": 0, 
    "electronic media and sleep": 0, 
    "endless computer": 0, 
    "evaluation of computers": 0, 
    "history of computing": 11, 
    "information appliances": 0, 
    "laser 50": 0, 
    "list of countries by computer exports": 0, 
    "microcomputer": 0, 
    "mixlink": 0, 
    "motion history images": 0, 
    "outline of computers": 0, 
    "pcaas": 0
  }
}
